export enum ConversationState {
  IDLE = 'idle',
  AWAITING_ITEM = 'awaiting_item',
  AWAITING_VARIANT = 'awaiting_variant',
  AWAITING_QUANTITY = 'awaiting_quantity',
  AWAITING_CONFIRMATION = 'awaiting_confirmation',
  AWAITING_PAYMENT = 'awaiting_payment',
  PAYMENT_COMPLETED = 'payment_completed',
  AWAITING_PAYMENT_SCREENSHOT = 'awaiting_payment_screenshot',
  HUMAN_TAKEOVER = 'human_takeover',
  AWAITING_NAME = 'awaiting_name',
  AWAITING_ADDRESS = 'awaiting_address',
  AWAITING_PROFILE_CONFIRMATION = 'awaiting_profile_confirmation',
  AWAITING_RECOVERY = 'awaiting_recovery',
}
