// ─── Action Executor ──────────────────────────────────────────────────────────
//
// Executes a validated Execution Plan by delegating to existing Business Services.
//
// CONTRACT:
//  - NEVER accesses repositories or the database directly.
//  - ONLY calls existing handler/service APIs.
//  - Processes actions sequentially in plan order.
//  - Returns a structured ActionExecutionReport — no WhatsApp reply generation.
//  - Never throws for individual action failures — wraps in FAILED result.
//  - The production message flow is NOT affected by this module.
//

import { logger } from '../../../infrastructure/logger/logger';
import {
  ExecutionAction,
  AddItemAction,
  RemoveItemAction,
  UpdateQuantityAction,
  UpdateVariantAction,
} from '../types/planner.types';
import {
  ActionValidationResult,
  ValidationContext,
  ActionValidatorService,
} from './action-validator.service';
import { SessionService } from '../../conversations/session.service';
import { MenuHandler } from '../../whatsapp/handlers/menu.handler';
import { CheckoutHandler } from '../../whatsapp/handlers/checkout.handler';
import { MenuMappingItem } from '../types/parser.types';
import { getDisplayName } from '../../../shared/utils/display-name.util';

// ─── Result Types ─────────────────────────────────────────────────────────────

export type ActionResultStatus = 'SUCCESS' | 'FAILED' | 'SKIPPED';

export interface ActionResult {
  /** Action type that was processed. */
  action: string;
  status: ActionResultStatus;
  /**
   * Structured data produced by this action.
   * Shape depends on the action type. Never a WhatsApp reply string — that is
   * generated by the response composer in Phase 3.
   */
  data?: Record<string, unknown>;
  /** Reason for FAILED or SKIPPED status. */
  reason?: string;
}

export interface ActionExecutionReport {
  results: ActionResult[];
  /** Total actions in the plan. */
  total: number;
  /** Number of successfully executed actions. */
  succeeded: number;
  /** Number of failed or skipped actions. */
  failed: number;
}

// ─── Execution Context ────────────────────────────────────────────────────────

/**
 * Runtime identifiers required by every executor method.
 */
export interface ExecutionContext {
  restaurantId: string;
  customerPhone: string;
  /** Full menu — already loaded by the caller to avoid multiple round-trips. */
  availableMenu: MenuMappingItem[];
}

// ─── Service ──────────────────────────────────────────────────────────────────

export class ActionExecutorService {
  private readonly validator: ActionValidatorService;
  private readonly sessionService: SessionService;
  private readonly menuHandler: MenuHandler;
  private get checkoutHandler(): any {
    const { CheckoutHandler } = require('../../whatsapp/handlers/checkout.handler');
    return new CheckoutHandler();
  }

  constructor() {
    this.validator = new ActionValidatorService();
    this.sessionService = new SessionService();
    this.menuHandler = new MenuHandler();
  }

  // ─── Public API ─────────────────────────────────────────────────────────────

  /**
   * Executes a list of pre-validated ActionValidationResults sequentially.
   *
   * @param validatedActions - Output of ActionValidatorService.validateAll()
   * @param execCtx          - Runtime identifiers (restaurantId, customerPhone, menu)
   * @returns ActionExecutionReport — structured results, never throws.
   */
  public async executeAll(
    validatedActions: ActionValidationResult[],
    execCtx: ExecutionContext,
  ): Promise<ActionExecutionReport> {
    const results: ActionResult[] = [];

    for (const { action, validation } of validatedActions) {
      if (!validation.valid) {
        results.push({
          action: action.type,
          status: 'SKIPPED',
          reason: validation.reason,
        });
        logger.warn(
          { action: action.type, reason: validation.reason },
          'ActionExecutor: action skipped (validation failed)',
        );
        continue;
      }

      const result = await this.executeSingle(action, validation, execCtx);
      results.push(result);
    }

    const succeeded = results.filter((r) => r.status === 'SUCCESS').length;
    const failed = results.filter((r) => r.status !== 'SUCCESS').length;

    logger.info(
      { total: results.length, succeeded, failed },
      'ActionExecutor: plan execution complete',
    );

    return { results, total: results.length, succeeded, failed };
  }

  // ─── Single Action Dispatch ───────────────────────────────────────────────

  private async executeSingle(
    action: ExecutionAction,
    validation: { resolvedMenuItem?: any; resolvedVariant?: any },
    execCtx: ExecutionContext,
  ): Promise<ActionResult> {
    try {
      switch (action.type) {
        case 'ADD_ITEM':
          return await this.executeAddItem(action, validation, execCtx);

        case 'REMOVE_ITEM':
          return await this.executeRemoveItem(action, validation, execCtx);

        case 'UPDATE_QUANTITY':
          return await this.executeUpdateQuantity(action, validation, execCtx);

        case 'UPDATE_VARIANT':
          return await this.executeUpdateVariant(action, validation, execCtx);

        case 'VIEW_CART':
          return await this.executeViewCart(execCtx);

        case 'CLEAR_CART':
          return await this.executeClearCart(execCtx);

        case 'VIEW_MENU':
          return this.executeViewMenu(execCtx);

        case 'CHECKOUT':
          return await this.executeCheckout(execCtx);

        case 'GREETING':
          return { action: 'GREETING', status: 'SUCCESS', data: {} };

        case 'SMALL_TALK':
          return { action: 'SMALL_TALK', status: 'SUCCESS', data: { topic: (action as any).topic } };

        case 'ASK_KNOWLEDGE':
          return { action: 'ASK_KNOWLEDGE', status: 'SUCCESS', data: { question: (action as any).question } };

        case 'ASK_PRICE':
          return this.executeAskPrice(action, validation, execCtx);

        case 'SEARCH_ITEM':
          return this.executeSearchItem(action, execCtx);

        case 'CHECK_PAYMENT_STATUS':
          return { action: 'CHECK_PAYMENT_STATUS', status: 'SUCCESS', data: {} };

        case 'REPEAT_LAST_ORDER':
          return { action: 'REPEAT_LAST_ORDER', status: 'SUCCESS', data: {} };

        case 'UNKNOWN':
          return { action: 'UNKNOWN', status: 'SKIPPED', reason: 'Intent not understood' };

        default:
          return {
            action: (action as any).type,
            status: 'FAILED',
            reason: `Unsupported action type: ${(action as any).type}`,
          };
      }
    } catch (error) {
      logger.error({ error, action }, 'ActionExecutor: unexpected error executing action');
      return {
        action: action.type,
        status: 'FAILED',
        reason: error instanceof Error ? error.message : 'Unexpected error',
      };
    }
  }

  // ─── Action Implementations ───────────────────────────────────────────────

  private async executeAddItem(
    action: AddItemAction,
    validation: { resolvedMenuItem?: any; resolvedVariant?: any },
    execCtx: ExecutionContext,
  ): Promise<ActionResult> {
    const menuItem = validation.resolvedMenuItem;
    const variant = validation.resolvedVariant;

    // 1. If item has variants but none was resolved, transition FSM to AWAITING_VARIANT and wait
    if (menuItem.variants && menuItem.variants.length > 0 && !variant) {
      await this.sessionService.executeSessionAction(
        execCtx.restaurantId,
        execCtx.customerPhone,
        async () => ({
          event: {
            name: 'NEED_VARIANT',
            payload: {
              menuItemId: menuItem.id,
              itemName: menuItem.name,
              quantity: action.quantity,
              customization: (action as any).customization,
            },
          },
        }),
      );

      logger.info({ item: menuItem.name }, 'ActionExecutor: ADD_ITEM needs variant');
      return {
        action: 'ADD_ITEM',
        status: 'SUCCESS',
        data: {
          needsVariant: true,
          menuItemId: menuItem.id,
          itemName: menuItem.name,
          quantity: action.quantity,
        },
      };
    }

    // 2. Otherwise, resolve price and add atomically
    const unitPrice: number = variant?.price ?? menuItem?.basePrice ?? 0;
    const variantId: string | undefined = variant?.id;

    await this.sessionService.executeSessionAction(
      execCtx.restaurantId,
      execCtx.customerPhone,
      async () => ({
        event: {
          name: 'ITEM_ADDED',
          payload: {
            menuItemId: menuItem.id,
            quantity: action.quantity,
            unitPrice,
            variantId,
          },
        },
      }),
    );

    const displayName = getDisplayName(
      {
        itemName: menuItem.name,
        variantName: variant?.variantName,
        variantId,
      },
      execCtx.availableMenu,
    );

    logger.info(
      { item: displayName, quantity: action.quantity, unitPrice },
      'ActionExecutor: ADD_ITEM success',
    );

    return {
      action: 'ADD_ITEM',
      status: 'SUCCESS',
      data: {
        menuItemId: menuItem.id,
        itemName: displayName,
        variantId,
        variantName: variant?.variantName,
        quantity: action.quantity,
        unitPrice,
        lineTotal: action.quantity * unitPrice,
      },
    };
  }

  private async executeRemoveItem(
    action: RemoveItemAction,
    validation: { resolvedMenuItem?: any; resolvedVariant?: any },
    execCtx: ExecutionContext,
  ): Promise<ActionResult> {
    const menuItem = validation.resolvedMenuItem;
    const variantId = validation.resolvedVariant?.id;

    await this.sessionService.executeSessionAction(
      execCtx.restaurantId,
      execCtx.customerPhone,
      async () => ({
        event: {
          name: 'ITEM_REMOVED' as any,
          payload: { menuItemId: menuItem.id, variantId },
        },
      }),
    );

    const displayName = getDisplayName(
      { itemName: menuItem.name, variantName: validation.resolvedVariant?.variantName, variantId },
      execCtx.availableMenu,
    );

    logger.info({ item: displayName }, 'ActionExecutor: REMOVE_ITEM success');

    return {
      action: 'REMOVE_ITEM',
      status: 'SUCCESS',
      data: { menuItemId: menuItem.id, itemName: displayName, variantId },
    };
  }

  private async executeUpdateQuantity(
    action: UpdateQuantityAction,
    validation: { resolvedMenuItem?: any },
    execCtx: ExecutionContext,
  ): Promise<ActionResult> {
    const menuItem = validation.resolvedMenuItem;

    // Find current cart item to get variantId
    const session = await this.sessionService.getSession(
      execCtx.restaurantId,
      execCtx.customerPhone,
    );
    const cartItem = session.cart.items.find((ci) => ci.menuItemId === menuItem.id);
    if (!cartItem) {
      return { action: 'UPDATE_QUANTITY', status: 'FAILED', reason: `"${menuItem.name}" not in cart` };
    }

    const newQuantity = action.delta
      ? Math.max(1, cartItem.quantity + action.quantity)
      : Math.max(1, action.quantity);

    await this.sessionService.executeSessionAction(
      execCtx.restaurantId,
      execCtx.customerPhone,
      async () => ({
        event: {
          name: 'QUANTITY_UPDATED' as any,
          payload: { menuItemId: menuItem.id, variantId: cartItem.variantId, quantity: newQuantity },
        },
      }),
    );

    logger.info({ item: menuItem.name, newQuantity }, 'ActionExecutor: UPDATE_QUANTITY success');

    return {
      action: 'UPDATE_QUANTITY',
      status: 'SUCCESS',
      data: { menuItemId: menuItem.id, itemName: menuItem.name, quantity: newQuantity },
    };
  }

  private async executeUpdateVariant(
    action: UpdateVariantAction,
    validation: { resolvedMenuItem?: any; resolvedVariant?: any },
    execCtx: ExecutionContext,
  ): Promise<ActionResult> {
    const menuItem = validation.resolvedMenuItem;
    const targetVariant = validation.resolvedVariant;

    // Find the cart item with the "from" variant
    const session = await this.sessionService.getSession(
      execCtx.restaurantId,
      execCtx.customerPhone,
    );

    // Find a cart item for this menu item
    const cartItem = session.cart.items.find(
      (ci) => ci.menuItemId === menuItem?.id,
    );

    if (!cartItem) {
      return { action: 'UPDATE_VARIANT', status: 'FAILED', reason: 'Item not found in cart' };
    }

    await this.sessionService.executeSessionAction(
      execCtx.restaurantId,
      execCtx.customerPhone,
      async () => ({
        event: {
          name: 'VARIANT_UPDATED' as any,
          payload: {
            menuItemId: menuItem.id,
            fromVariantId: cartItem.variantId,
            toVariantId: targetVariant?.id,
            toUnitPrice: targetVariant?.price ?? cartItem.unitPrice,
          },
        },
      }),
    );

    logger.info(
      { item: menuItem?.name, from: action.from, to: action.to },
      'ActionExecutor: UPDATE_VARIANT success',
    );

    return {
      action: 'UPDATE_VARIANT',
      status: 'SUCCESS',
      data: {
        menuItemId: menuItem?.id,
        itemName: menuItem?.name,
        fromVariant: action.from,
        toVariantName: targetVariant?.variantName,
        toVariantPrice: targetVariant?.price,
      },
    };
  }

  private async executeViewCart(execCtx: ExecutionContext): Promise<ActionResult> {
    const session = await this.sessionService.getSession(
      execCtx.restaurantId,
      execCtx.customerPhone,
    );

    const cartItems = session.cart.items.map((ci) => {
      const itemName = getDisplayName(ci, execCtx.availableMenu);
      return {
        menuItemId: ci.menuItemId,
        variantId: ci.variantId,
        itemName,
        quantity: ci.quantity,
        unitPrice: ci.unitPrice,
        lineTotal: ci.quantity * ci.unitPrice,
      };
    });

    const total = cartItems.reduce((sum, ci) => sum + ci.lineTotal, 0);

    return {
      action: 'VIEW_CART',
      status: 'SUCCESS',
      data: { items: cartItems, total, isEmpty: cartItems.length === 0 },
    };
  }

  private async executeClearCart(execCtx: ExecutionContext): Promise<ActionResult> {
    await this.sessionService.executeSessionAction(
      execCtx.restaurantId,
      execCtx.customerPhone,
      async () => ({ event: { name: 'RESET' } }),
    );

    return { action: 'CLEAR_CART', status: 'SUCCESS', data: {} };
  }

  private executeViewMenu(execCtx: ExecutionContext): ActionResult {
    const menuText = this.menuHandler.handle(execCtx.availableMenu);
    return {
      action: 'VIEW_MENU',
      status: 'SUCCESS',
      data: { menuText, itemCount: execCtx.availableMenu.length },
    };
  }

  private async executeCheckout(execCtx: ExecutionContext): Promise<ActionResult> {
    // Delegates to the existing CheckoutHandler — no business logic duplicated
    const reply = await this.checkoutHandler.handle(
      execCtx.restaurantId,
      execCtx.customerPhone,
    );

    return {
      action: 'CHECKOUT',
      status: 'SUCCESS',
      data: { checkoutReply: reply },
    };
  }

  private executeAskPrice(
    action: any,
    validation: { resolvedMenuItem?: any; resolvedVariant?: any },
    execCtx: ExecutionContext,
  ): ActionResult {
    const menuItem = validation.resolvedMenuItem;
    if (!menuItem) {
      return { action: 'ASK_PRICE', status: 'FAILED', reason: 'Item not found' };
    }

    const priceInfo = validation.resolvedVariant
      ? { price: validation.resolvedVariant.price, variant: validation.resolvedVariant.variantName }
      : menuItem.variants.length > 0
        ? { variants: menuItem.variants.map((v: any) => ({ name: v.variantName, price: v.price })) }
        : { price: menuItem.basePrice };

    return {
      action: 'ASK_PRICE',
      status: 'SUCCESS',
      data: { itemName: menuItem.name, priceInfo },
    };
  }

  private executeSearchItem(action: any, execCtx: ExecutionContext): ActionResult {
    const q = action.query.toLowerCase();
    const matches = execCtx.availableMenu.filter(
      (m) =>
        m.name.toLowerCase().includes(q) ||
        m.aliases.some((a) => a.toLowerCase().includes(q)),
    );

    return {
      action: 'SEARCH_ITEM',
      status: 'SUCCESS',
      data: {
        query: action.query,
        found: matches.length > 0,
        items: matches.map((m) => ({
          name: m.name,
          basePrice: m.basePrice,
          variants: m.variants.map((v) => ({ name: v.variantName, price: v.price })),
        })),
      },
    };
  }

  // ─── Context Builder ──────────────────────────────────────────────────────

  /**
   * Builds the ValidationContext from live session data.
   * Called by the orchestrator before validating actions.
   */
  public buildValidationContext(
    session: {
      cart: { items: any[] };
      state: string;
    },
    availableMenu: MenuMappingItem[],
    hasPendingPayment = false,
    hasActiveOrder = false,
  ): ValidationContext {
    return {
      menu: availableMenu,
      cartItems: session.cart.items,
      conversationState: session.state,
      hasPendingPayment,
      hasActiveOrder,
    };
  }
}
