import crypto from 'crypto';
import { env } from '../../config/env';

export class WhatsAppWebhookValidation {
  /**
   * Verifies the verification token sent by WhatsApp Cloud API during webhook setup.
   */
  public verifyToken(mode: string, token: string): boolean {
    const expectedToken = process.env.WHATSAPP_VERIFY_TOKEN || 'restroex-verify-token-pilot';
    return mode === 'subscribe' && token === expectedToken;
  }

  /**
   * Verifies the payload signature using the WhatsApp App Secret key to ensure authenticity.
   * X-Hub-Signature-256 header contains the SHA256 signature generated by WhatsApp.
   */
  public verifySignature(payload: string, signatureHeader: string): boolean {
    const appSecret = process.env.WHATSAPP_APP_SECRET;
    if (!appSecret) {
      // If no secret configured in pilot environment, log warning and bypass check
      return true;
    }

    if (!signatureHeader) {
      return false;
    }

    // signatureHeader format: sha256=HEX_SIGNATURE
    const parts = signatureHeader.split('=');
    if (parts.length !== 2 || parts[0] !== 'sha256') {
      return false;
    }

    const expectedSignature = parts[1];
    const computedSignature = crypto
      .createHmac('sha256', appSecret)
      .update(payload)
      .digest('hex');

    return crypto.timingSafeEqual(
      Buffer.from(computedSignature, 'hex'),
      Buffer.from(expectedSignature || '', 'hex')
    );
  }
}
